version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: circleci/mongo:4.0.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "go.sum" }}
            - deps-{{ .Branch }}-
            - deps-

      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 10s

      - run:
          name: Install ginkgo
          command: go get github.com/onsi/ginkgo/ginkgo

      - run:
          name: Download dependencies
          command: go mod download

      - run:
          name: Run tests
          command: |
            make coverage-ci
            bash <(curl -s https://codecov.io/bash)

      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

      - store_test_results:
          path: test-results
